### ISSUE TITLE
ElasticAPMSourceMapPlugin is not a constructor

### ISSUE THREAD

**Issue by adolt** [wuct/elastic-apm-sourcemap-webpack-plugin#12]
Hi, I'm using create-react-app, and i encounter this
![image](https://user-images.githubusercontent.com/25565814/53858907-dd6ee000-4016-11e9-8e97-9491d436e208.png)

Here's my webpack config
![image](https://user-images.githubusercontent.com/25565814/53858977-1eff8b00-4017-11e9-818a-0add2bf786d6.png)

I know I can use
`const ElasticAPMSourceMapPlugin = require('elastic-apm-sourcemap-webpack-plugin').default`
to solve this. But why?

**Comment by wuct** [comment]
Thanks for reporting. It is because we are using Babel to compile the code and Babel does not do `module.exports = ElasticAPMSourceMapPlugin`. We can add this [plugin](https://www.npmjs.com/package/babel-plugin-add-module-exports) to change its behavior, but we will also make a breaking change. 
I will update the README to clarify it.

**Comment by adolt** [comment]
Thanks!
